version: "3.9"

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user1
      - MONGO_INITDB_ROOT_PASSWORD=banana123
    volumes:
      - "mongo_data:/data/db"
volumes:
  mongo_data: {}